---
- hosts: nginx
  remote_user: root
  become: true

  tasks:

    - name: Update feeds
      cron:
        name: Update feeds
        user: "{{ user }}"
        hour: "*/1"
        minute: "0"
        job: curl "https://{{ domain }}/__cron/sync-feeds-batch"

    - name: Update users
      cron:
        name: Update users
        user: "{{ user }}"
        hour: "*/1"
        minute: "30"
        job: curl "https://{{ domain }}/__cron/sync-users-batch"
